### ISSUE TITLE
do not convert string literals to non-const pointer type

### ISSUE THREAD

**Issue by yumetodo** [MaverickTse/SigContrastFastAviUtl#2]
According to C++11 standerd, type of string literals is const array.

``` cpp
"arikitari_na_string";//const char[20]
```

So, 

``` cpp
char* en_name[] = { "Midtone", "Strength" };
```

is illegal.

``` cpp
static char en_name_1[] = "Midtone";
static char en_name_2[] = "Strength";
char* en_name[] = { en_name_1, en_name_2 };
```

need to fix like above.

**Comment by MaverickTse** [comment]
No. I'm not going to write that redundant code. The compiler did not complaint anyway so I don't see why it is illegal.
The more important reason is I don't want to break AviUtl SDK's convention, which has been proven working.
