### ISSUE TITLE
stop to use macro-constant-value to specify array size

### ISSUE THREAD

**Issue by yumetodo** [MaverickTse/SigContrastFastAviUtl#3]
``` cpp
#define TRACK_N 2
```

such constant value reduce the serviceability.

use function like [`std::size(C++17)`](http://en.cppreference.com/w/cpp/iterator/size)

**Comment by MaverickTse** [comment]
Again, that is AviUtl SDK convention. Changing that may break even more convention.

**Comment by yumetodo** [comment]
> Changing that may break even more convention.

`TRACK_N` macro is required only for constructing `FILTER_DLL` structure. And It's replaceable to `std::size(C++17)`, there is no breaking change.

**Comment by MaverickTse** [comment]
man! why are you so obsessed with the latest standard!?
You can even go as far as wrapping all the UI code in a custom Class with automatic error checking... I just feel not worthing the trouble as long as things works.

**Comment by yumetodo** [comment]
``` cpp
template<class T, size_t N> constexpr size_t size( const T (&)[N] ) noexcept;
```

just add one line and you can remove 2 line and boost maintenanceability, I think.

**Comment by MaverickTse** [comment]
That increase quite a bit of overhead...
Unless the UI change frequently, there is no incentive to use class/template other than a simple number
